### ISSUE TITLE
If can't connect to server, work on local

### ISSUE THREAD

**Issue by pocke** [pocke/lemonade#11]
lemonade server に接続できない時、ローカル内でxdg-openなどを動かしたい

Ref: https://github.com/vim-jp/vital.vim/pull/425#issuecomment-210964856

**Comment by pocke** [comment]
@tyru サーバーに接続出来ない場合にローカルホストで動作するよう修正 && リリースしました。
提案ありがとうございました :bow: 

https://github.com/pocke/lemonade/releases/tag/v1.0.0

**Comment by tyru** [comment]
ありがとうございます！
