### ISSUE TITLE
Plugin for vim/neovim?

### ISSUE THREAD

**Issue by ninrod** [pocke/lemonade#17]
@pocke thanks for the awesome repo. Is a vim/neovim plugin on your radar?

**Comment by pocke** [comment]
I use open-browser.vim https://github.com/tyru/open-browser.vim
You can use the plugin for `lemonade open`.

And neovim supports `lemonade copy / paste`. https://github.com/neovim/neovim/blob/master/runtime/doc/nvim_clipboard.txt#L25
However, I don't use neovim. So, I don't know in detail.

**Comment by ninrod** [comment]
ok thanks.
